---
- name: Configure dnsmasq on localhost
  hosts: localhost
  become: true
  vars:
    dnsmasq_config_dir: /etc/dnsmasq.d
    testnet_domain: sandbox.local
    libvirt_gateway: 192.168.50.1
    dnsmasq_sandbox_config: |
      server=/{{ testnet_domain }}/{{ libvirt_gateway }}
      listen-address=127.0.0.1
      bind-interfaces
      domain-needed
      bogus-priv

  tasks:
    - name: Ensure dnsmasq is present
      package:
        name: dnsmasq
        state: present

    - name: Ensure dnsmasq is running
      ansible.builtin.service:
        name: dnsmasq
        state: started
        enabled: true

    - name: Configure dnsmasq for local test domain
      ansible.builtin.copy:
        dest: "{{ dnsmasq_config_dir }}/sandbox.conf"
        content: "{{ dnsmasq_sandbox_config }}"
        owner: root
        group: root
        mode: 0644
      notify: Restart dnsmasq

    - name: Ensure localhost is the system DNS resolver
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver'
        line: 'nameserver 127.0.0.1'
        insertafter: BOF
        state: present

  handlers:
    - name: Restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted
