# security/tasks/apparmor.yaml
---
- name: Ensure apparmor and apparmor-utils is present
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    with_items:
      - apparmor
      - apparmor-utils

- name: Start apparmor service
  ansible.builtin.service:
    name: apparmor
    state: started
    enabled: true

# TODO: define custom rules if necessary

- name: Register aa-status output
  ansible.builtin.shell:
    command: aa-status --complaining
    register: aa_status_complaining

- name: Get processes in complain mode
  ansible.builtin.debug:
    msg: "WARNING: Some AppArmor processes are in complain mode"
  when: aa_status_complaining.stdout > 0

