# interfaces/tasks/iface_wan.yaml
---
- name: Insert marker for the WAN config block
  ansible.builtin.shell: |
    awk '
      BEGIN { in_sysctl = 0; in_interfaces = 0 }
      /<sysctl>/  { in_sysctl = 1 }
      /<\/sysctl>/  { in_sysctl = 0 }
      in_sysctl && /<interfaces>/ { in_interfaces = 1 }
      in_interfaces && /<\/interfaces>/ { in_interfaces = 0 }
      in_sysctl && in_interfaces && /<wan>/ {
        print "<!-- ANSIBLE WAN BLOCK -->"
      }
      { print }
    ' /conf/config.xml > /conf/config.tmp.xml && mv /conf/config.tmp.xml /conf/config.xml

- name: Configure WAN interface
  ansible.builtin.blockinfile:
    path: /conf/config.xml
    block: "{{ lookup('template', 'wan.xml.j2') }}"
    insertafter: "<!-- ANSIBLE WAN BLOCK -->"
    state: present
    backup: true
    create: false
