# interfaces/tasks/iface_wan.yaml
---
- name: Configure WAN interface
  ansible.builtin.blockinfile:
    path: /conf/config.xml
    marker: ""
    block: "{{ lookup('template', 'wan.xml.j2') }}"
    insertafter: "<interfaces>"
    state: present
    backup: true
    create: false
