---
- hosts: localhost
  gather_facts: true

  tasks:
    #- name: Install display display server
    #  include_tasks: tasks/x-display-server.yaml
    
    - name: Install Xorg
      ansible.builtin.apt:
        name: xorg
        state: present
    
    #- name: Install window manager
    #  include_tasks: tasks/window-manager.yaml 

    - name: Install i3
      ansible.builtin.apt:
        name: i3
        state: present
      become: true

    - name: Install shell
      include_tasks: tasks/shell.yaml

    - name: Install graphics driver
      include_tasks: tasks/gfx-driver.yaml

    - name: Install development tools
      include_tasks: tasks/devtools.yaml

    - name: Setup dotfiles
      include_tasks: tasks/dotfiles.yaml

