# dns/tasks/unbound.yaml
---
# - name: Build unbound-builder image
#   community.docker.docker_image_build:
#     name: unbound-builder
#     path: /tmp/docker-build/
#     dockerfile: Dockerfile
#   delegate_to: localhost
#
# - name: Create containerized build server
#   community.docker.docker_container:
#     name: unbound-builder 
#     image: unbound-builder
#     state: started
#     volumes:
#       - "{{ role_path }}/files/unbound:/src"
#   delegate_to: localhost

- name: Install unbound
  ansible.builtin.apt:
    name: ["unbound", "unbound-anchor"]
    state: present
    update_cache: true

- name: Setup trust anchor
  ansible.builtin.command: unbound-anchor -a /var/lib/unbound/root.key

- name: Configure unbound
  ansible.builtin.template:
    src: "{{ lookup('template', unbound.conf.j2) }}"
    dest: /etc/unbound/unbound.conf

- name: Configure interface resolver
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    line: ' dns-nameservers 127.0.0.1'
    insertafter: '^iface vmbr0 inet static'
    state: present
