[global]
keyboard = "no"
country = "no"
fqdn = "pve-local.test"
mailto = "mail@no.invalid"
timezone = "Europe/Oslo"
root-password = "root1234"
root-ssh-keys = [
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCvLh/BVOEFfNNINoNAtGsMhIssZOydJLyLbRbt4SgMBeIUAlAVh68g4kSgVujHFkZlKsFnAfdaxqDjI6FyQH7g7+eVbVI5L+fb/MwZqgMiQUQjmebDKDHhMfBP4ivinYjiMVoBVMp998XBrOHS5NVFOQmQgq7l/6Bh1E65W07jfupJX9IAGnTZuiXQrJA1pr5YmC6zksSiKGyPmEkM7OdGb2d/k5q6Evj5atqLbuVDJSKhvZXeqN9cwnJyYhzrEahgXXapOl8wrIHIF1aC2miqGnw6yIPAj9K4go9KlJLshICM+HwnOVHbN9lJ1+0lO/D8z6vhJO84VQdTiJDpVN2WdEXpKgV29PrgMlhq/2WiPL8x3GC0gpudG0FFRl/bjS3aVqlxR/fW9Kd6IS/K5g5iHNS5nyh2UKaiZ3YCWuBJXW/pod+JvwAlscvuvDeHvcjkgBh7rKKXDorFxC/mJDKwyqw94LZ+EGjh7A8KEEGKVxPQkHf/9ovFHKPFyeHLf9GY1ui2iwkM5kHpcVTVAaLxibvpckmWrlquM01h6XKDY6tk/nE0C9db9hRAA1m4dJjXSss2XK3GmVf2BhwHk4/wAn1LFJy45h+g231ddSTCL1dhLVnFfwZ40Ak9jrfbkP8oBVBrwwkmGrrdUatMTtqIfTzaOg5JQo9v0l/d2VXkfQ== user@localhost.localdomain"
]

[network]
# TODO: iaw the TODO for first-boot, we use DHCP as of now
source = "from-dhcp"
# source = "from-answer"
# cidr="192.168.1.20/24"
# dns="192.168.1.10"
# gateway="192.168.1.10"
# # NOTE: need to know the UDEV property for the network interface
# udevadm info -q all -n ens18
# filter={ ID_NET_NAME_MAC = "enxe43d1afa379a" }

# NOTE: the real hardware is setup with ext4 for OS disk
# and raidz2 for data
[disk-setup]
filesystem = "ext4"
disk_list = ["sda"]

# TODO: creating the ISO with the script contents was not straight forward,
# will therefore add this feature later
# [first-boot]
# source = "from-iso"
# ordering = "before-network"
