---
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - g++
    - valgrind
    - gdb
    - clangd
    - ripgrep
    - unzip
    - luajit
    - build-essential
    - autoconf
    - libtool
  become: true

- name: Download cmake archive
  ansible.builtin.unarchive:
    src: https://github.com/Kitware/CMake/releases/download/v3.28.1/cmake-3.28.1.tar.gz
    dest: /home/rune/sources/cmake
    remote_src: true
    extra_opts:
      - --strip-components=1

- name: Build cmake
  ansible.builtin.shell:
    chdir: /home/rune/sources/cmake
    cmd: ./bootstrap && make && sudo make install
  become: true
  delegate_to: localhost

- name: Clone neovim repository
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    dest: /home/rune/sources/neovim

- name: Build neovim
  ansible.builtin.shell:
    chdir: /home/rune/sources/neovim
    cmd: make CMAKE_BUILD_TYPE=Release && sudo make install
  become: true

- name: Clone vcpkg repository
  ansible.builtin.git:
    repo: https://github.com/Microsoft/vcpkg.git
    dest: /opt/vcpkg
  become: true

#- name: Chmod vcpkg directory
#  ansible.builtin.file:
#    path: /opt/vcpkg
#    owner: rune
#    group: rune
#    recurse: true

- name: Build vcpkg
  ansible.builtin.shell:
    cmd: /opt/vcpkg/bootstrap-vcpkg.sh -disableMetrics

- name: Create vcpkg symlink to make it executable from PATH
  ansible.builtin.file:
    src: /opt/vcpkg/vcpkg
    dest: /usr/local/bin/vcpkg
    state: link

- name: Clone git semantic commits
  ansible.builtin.git:
    repo: https://github.com/fteem/git-semantic-commits
    dest: "{{ lookup('env', 'HOME') }}/.config/git-semantic-commits"

- name: Build git semantic commits
  ansible.builtin.shell:
    chdir: "{{ lookup('env', 'HOME') }}/.config/git-semantic-commits"
    cmd: ./install.sh
