# interfaces/tasks/iface_lan.yaml
---
- name: Insert marker for the LAN interface config block
  ansible.builtin.shell: |
    awk '
      BEGIN { in_sysctl = 0; in_interfaces = 0 }
      /<sysctl>/  { in_sysctl = 1 }
      /<\/sysctl>/  { in_sysctl = 0 }
      in_sysctl && /<interfaces>/ { in_interfaces = 1 }
      in_interfaces && /<\/interfaces>/ { in_interfaces = 0 }
      in_sysctl && in_interfaces && /<lan>/ {
        print "<!-- ANSIBLE LAN BLOCK -->"
      }
      { print }
    ' /conf/config.xml > /conf/config.tmp.xml && mv /conf/config.tmp.xml /conf/config.xml

- name: Insert marker for the LAN DHCP config block
  ansible.builtin.shell: |
    awk '
      BEGIN { in_sysctl = 0; in_interfaces = 0 }
      /<sysctl>/  { in_sysctl = 1 }
      /<\/sysctl>/  { in_sysctl = 0 }
      in_sysctl && /<dhcpd>/ { in_dhcpd = 1 }
      in_dhcpd && /<\/dhcpd>/ { in_dhcpd = 0 }
      in_sysctl && in_dhcpd && /<lan>/ {
        print "<!-- ANSIBLE LAN DHCP BLOCK -->"
      }
      { print }
    ' /conf/config.xml > /conf/config.tmp.xml && mv /conf/config.tmp.xml /conf/config.xml

- name: Configure LAN interface
  ansible.builtin.blockinfile:
    path: /conf/config.xml
    block: "{{ lookup('template', 'lan.xml.j2') }}"
    insertafter: "<!-- ANSIBLE LAN BLOCK -->"
    state: present
    backup: true
    create: false

- name: Configure LAN DHCP
  ansible.builtin.blockinfile:
    path: /conf/config.xml
    block: "{{ lookup('template', 'lan_dhcp.xml.j2') }}"
    insertafter: "<!-- ANSIBLE LAN DHCP BLOCK -->"
    state: present
    backup: true
    create: false

