# prelude/tasks/main.yaml
---
- name: Ensure custom templates directory exists
  ansible.builtin.file:
    path: "{{ templates_dir.custom }}"
    state: directory
    owner: root
    group: root
    mode: 0700

