---
- hosts: localhost
  become: true
  vars:
    libvirt_pool: "default"
    usb_image_path: "/var/lib/libvirt/images/usb-stick.qcow2"
    usb_image_size_gb: 1
    usb_mount_temp: "/mnt/bootstrap-usb"
    usb_label: "BOOTSTRAP"
    nat_interface: "virbr10"
    # Physical interface connected to internet
    nat_postrouting_iface: "wlan0"

  tasks:
  - name: Setup virtual USB image
    include_tasks: usb_image.yaml

  - name: Manage routed NAT for libvirt
    include_tasks: routed_nat.yaml

