# usb_image.yaml
---
- name: Check if USB image exists
  ansible.builtin.stat:
    path: "{{ usb_image_path }}"
  register: usb_image_stat

- name: Create qcow2 USB stick image if missing
  ansible.builtin.command: qemu-img create -f qcow2 "{{ usb_image_path }}" "{{ usb_image_size_gb }}G"
  when: not usb_image_stat.stat.exists

- name: Load nbd kernel module
  ansible.builtin.shell: modprobe nbd max_part=8
  args:
    warn: false

- name: Connect USB image to nbd device
  ansible.builtin.command: qemu-nbd -c /dev/nbd0 "{{ usb_image_path }}"
  when: not usb_image_stat.stat.exists

- name: Create FAT filesystem on /dev/nbd0 if image was newly created
  ansible.builtin.filesystem:
    fstype: vfat
    dev: /dev/nbd0
  when: not usb_image_stat.stat.exists

- name: Create temporary mount point
  ansible.builtin.file:
    path: "{{ usb_imagemount_temp }}"
    state: directory

- name: Mount USB image partition
  ansible.builtin.mount:
    path: "{{ usb_mount_temp }}"
    src: /dev/nbd0
    fstype: vfat
    state: mounted

- name: Copy airgapped repo content into USB stick image
  ansible.builtin.copy:
    src: "./repo_content/"  # TODO: this is the local directory holding all resources to be found on the USB
    dest: "{{ usb_mount_temp }}/"
    owner: root
    group: root
    mode: "0755"
  # Note: make sure ./repo_content/ exists and has your packages, images, ISOs

- name: Unmount USB image
  ansible.builtin.mount:
    path: "{{ usb_mount_temp }}"
    state: unmounted

- name: Disconnect nbd device
  ansible.builtin.command: qemu-nbd -d /dev/nbd0

