# security/tasks/firewall.yaml
---
- name: Flush iptables filter
  ansible.builtin.iptables:
    chain: "{{ item }}"
    flush: true
  with_items:
    - INPUT
    - FORWARD
    - OUTPUT

- name: Flush iptables NAT
  ansible.builtin.iptables:
    table: nat
    chain: "{{ item }}"
    flush: true
  with_items:
    - INPUT
    - OUTPUT
    - PREROUTING
    - POSTROUTING

- name: Set default INPUT chain policy to DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

- name: Allow localhost traffic
  ansible.builtin.iptables:
    chain: INPUT
    source: 127.0.0.1
    jump: ACCEPT
  ignore_errors: true

- name: Open port for SSH
  ansible.builtin.iptables:
    chain: INPUT
    destination_port: 22
    jump: ACCEPT
    state: present
  ignore_errors: true

- name: Open port for DNS
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    jump: ACCEPT
    destination_port: "{{ dns_port }}"
    state: present
  ignore_errors: true

- name: Open port for certificate requests
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    jump: ACCEPT
    destination_port: 443
    state: present
  ignore_errors: true

- name: Save iptables rules to /etc/iptables/rules.v4
  ansible.builtin.command:
    cmd: iptables-save > /etc/iptables/rules.v4

- name: Apply iptables rules
  ansible.builtin.command:
    cmd: iptables-restore < /etc/iptables/rules.v4

